/**
 * What kind of figure each metric is (SPEC principle 11, Milestone 31): shown beside it
 * in every table that lists metrics, and in its definition card. The same kinds as
 * `record_type` in `config/metrics.yml`, which `tests/test_licences.py` keeps this in
 * step with — a static map, like `SURVEY_METRICS`, because a definition card names only
 * its metric and the pages are built without asking the API for it.
 */

export type RecordType =
  | "survey"
  | "administrative"
  | "determination"
  | "benchmark"
  | "calculated"
  | "modelled";

export const KIND_LABELS: Record<RecordType, string> = {
  survey: "Survey estimate",
  administrative: "Administrative records",
  determination: "Official determination",
  benchmark: "Published benchmark",
  calculated: "Calculated here",
  modelled: "Modelled estimate",
};

/** What each kind means, for the tag's own tooltip. */
export const KIND_MEANINGS: Record<RecordType, string> = {
  survey: "Estimated from a sample survey, so it carries a margin of error.",
  administrative: "Counted from official records, such as permits, deeds or the tax roll.",
  determination: "A figure an agency sets and publishes as its own, used exactly as published.",
  benchmark: "An average its publisher reports as a benchmark, without a margin of error.",
  calculated: "Worked out by this site from other figures, by a stated formula.",
  modelled: "Estimated by its publisher with a statistical model rather than counted.",
};

export const KINDS: Record<string, RecordType> = {
  nj_ah_present_need: "modelled",
  nj_ah_prospective_need: "modelled",
  nj_ah_completed_units: "administrative",
  nj_ah_trust_balance: "administrative",
  acs_median_rent_studio: "survey",
  acs_median_rent_1br: "survey",
  acs_median_rent_2br: "survey",
  acs_median_rent_3br: "survey",
  acs_median_rent_4br: "survey",
  acs_rent_lower_quartile: "survey",
  acs_rent_upper_quartile: "survey",
  acs_owner_costs_mortgage: "survey",
  acs_owner_costs_no_mortgage: "survey",
  acs_renter_severe_burden: "survey",
  acs_owner_severe_burden: "survey",
  acs_share_detached: "survey",
  acs_share_attached: "survey",
  acs_share_2_4_units: "survey",
  acs_share_5_19_units: "survey",
  acs_share_20plus_units: "survey",
  acs_share_mobile_homes: "survey",
  acs_median_year_built: "survey",
  acs_share_built_2000_later: "survey",
  acs_share_built_1980_1999: "survey",
  acs_share_built_1940_1979: "survey",
  acs_share_built_pre_1940: "survey",
  acs_share_0_1_bedrooms: "survey",
  acs_share_2_bedrooms: "survey",
  acs_share_3_bedrooms: "survey",
  acs_share_4plus_bedrooms: "survey",
  acs_overcrowded_share: "survey",
  acs_lacking_plumbing_share: "survey",
  acs_lacking_kitchen_share: "survey",
  acs_avg_household_size: "survey",
  acs_no_vehicle_share: "survey",
  acs_rental_vacancy_rate: "survey",
  acs_homeowner_vacancy_rate: "survey",
  acs_vacant_seasonal_share: "survey",
  acs_vacant_other_share: "survey",
  acs_heat_gas_share: "survey",
  acs_heat_electric_share: "survey",
  acs_heat_oil_share: "survey",
  acs_heat_propane_share: "survey",
  acs_heat_other_share: "survey",
  acs_commute_transit_share: "survey",
  acs_work_from_home_share: "survey",
  acs_commute_drove_alone_share: "survey",
  acs_commute_walked_share: "survey",
  acs_mean_commute_minutes: "survey",
  acs_commute_60plus_share: "survey",
  acs_living_alone_share: "survey",
  acs_married_couple_share: "survey",
  acs_with_children_share: "survey",
  acs_disability_share: "survey",
  acs_homeownership_rate: "survey",
  acs_median_gross_rent: "survey",
  acs_median_hh_income: "survey",
  acs_median_electricity: "survey",
  acs_median_gas: "survey",
  acs_median_home_insurance: "survey",
  acs_median_home_value: "survey",
  acs_median_other_fuel: "survey",
  acs_median_water_sewer: "survey",
  acs_population: "survey",
  acs_renter_cost_burden: "survey",
  acs_renters_paying_utilities: "survey",
  acs_vacancy_rate: "survey",
  acs_housing_units: "survey",
  chas_owner_cost_burden: "survey",
  chas_renter_cost_burden: "survey",
  chas_renter_severe_burden: "survey",
  fhfa_hpi: "modelled",
  fhfa_hpi_all_transactions: "modelled",
  fhfa_hpi_county: "modelled",
  saipe_median_hh_income: "modelled",
  fmr_to_income: "calculated",
  hud_area_median_income: "determination",
  hud_fmr_2br: "determination",
  hud_fmr_0br: "determination",
  hud_fmr_1br: "determination",
  hud_fmr_3br: "determination",
  hud_fmr_4br: "determination",
  hud_safmr_0br: "determination",
  hud_safmr_1br: "determination",
  hud_safmr_2br: "determination",
  hud_safmr_3br: "determination",
  hud_safmr_4br: "determination",
  hud_income_limit_80: "determination",
  modiv_median_assessed_value: "administrative",
  modiv_median_lot_acres: "administrative",
  modiv_median_tax_bill: "administrative",
  modiv_median_year_built: "administrative",
  modiv_multifamily_share: "administrative",
  modiv_residential_parcels: "administrative",
  modiv_vacant_land_share: "administrative",
  mortgage_rate_30y: "benchmark",
  mortgage_rate_30y_weekly: "benchmark",
  net_migration_returns: "administrative",
  irs_inflow_returns: "administrative",
  irs_outflow_returns: "administrative",
  irs_net_migration_per_1000: "administrative",
  irs_inflow_agi_per_return: "administrative",
  irs_outflow_agi_per_return: "administrative",
  irs_nonmigrant_agi_per_return: "administrative",
  irs_arrival_income_ratio: "administrative",
  nj_director_ratio: "determination",
  nj_effective_tax_rate: "determination",
  nj_general_tax_rate: "determination",
  pep_population: "modelled",
  permits_total_units: "administrative",
  price_to_ami: "calculated",
  price_to_income: "calculated",
  rent_to_income: "calculated",
  sr1a_median_sale_price: "administrative",
  sr1a_sales_count: "administrative",
  sr1a_turnover_per_1000: "calculated",
  sr1a_price_lower_quartile: "administrative",
  sr1a_price_upper_quartile: "administrative",
  sr1a_median_sale_price_12m: "administrative",
  sr1a_median_year_built_sold: "administrative",
  sr1a_median_price_per_sqft: "administrative",
  sr1a_median_sales_ratio: "administrative",
  nj_revaluation_year: "determination",
  // Milestone 39: DCA's Construction Reporter, and the rate per 1,000 homes.
  nj_units_certified: "administrative",
  nj_units_certified_1_2: "administrative",
  nj_units_certified_multi: "administrative",
  nj_units_certified_mixed: "administrative",
  nj_units_demolished: "administrative",
  nj_net_units_added: "calculated",
  nj_certificates_reporting_share: "calculated",
  nj_demolitions_reporting_share: "calculated",
  nj_net_units_per_1000: "calculated",
  // Milestone 40: shares of homes are the platform's overlay of 2020's homes on the
  // publishers' maps; claims and site counts are the publishers' records, counted.
  fema_flood_homes_share: "calculated",
  fema_flood_homes_share_moderate: "calculated",
  fema_flood_homes: "calculated",
  fema_mapped_homes_share: "calculated",
  njdep_tidal_homes_share: "calculated",
  fema_flood_claims: "administrative",
  fema_flood_claims_paid: "administrative",
  njdep_sites_open: "administrative",
  njdep_sites_post_remedy: "administrative",
  njdep_sites_heating_oil: "administrative",
  water_homes_share_public: "calculated",
  water_homes_share_violation: "calculated",
  // Milestone 45: LODES's count of jobs is the Census Bureau's record; the shares and
  // nearness to transit are the platform's arithmetic on it and on BTS's stops.
  lodes_resident_jobs: "administrative",
  lodes_work_same_town_share: "calculated",
  lodes_work_home_county_share: "calculated",
  lodes_work_other_nj_share: "calculated",
  lodes_work_nyc_share: "calculated",
  lodes_work_pennsylvania_share: "calculated",
  lodes_work_other_state_share: "calculated",
  transit_rail_homes_share: "calculated",
  transit_bus_homes_share: "calculated",
  transit_any_homes_share: "calculated",
  // Milestone 48: HMDA's count is the lenders' record; the medians and shares are the
  // platform's arithmetic on it. FHA's limit is HUD's determination.
  hmda_purchase_loans: "administrative",
  hmda_median_rate: "calculated",
  hmda_median_loan_amount: "calculated",
  hmda_median_ltv: "calculated",
  hmda_median_loan_costs: "calculated",
  hmda_median_income: "calculated",
  hmda_conventional_share: "calculated",
  hmda_fha_share: "calculated",
  hmda_va_share: "calculated",
  hmda_denial_rate: "calculated",
  hmda_denial_dti_share: "calculated",
  hmda_denial_value_share: "calculated",
  hmda_denial_credit_share: "calculated",
  hud_fha_limit_1unit: "determination",
  unemployment_rate: "modelled",
  zhvi_sfr: "modelled",
  zori_all: "modelled",
};

export function kindOf(metricId: string): RecordType | null {
  return KINDS[metricId] ?? null;
}
