"""Model-written explanations, served as interpretation and labeled as such.

Read-only, like every other endpoint. `hip explain` generates and stores; this reads a
row back (ARCHITECTURE #6). No request path loads a model — a model load is seconds and
gigabytes, and on 16GB of unified memory a resident model would push the rest of the
platform into swap.

The response is shaped so a consumer cannot present this as a measurement by accident.
`kind` is the literal string `interpretation`, the generating model is named, and `stale`
says whether the numbers moved since the text was written. A client that ignores all
three has to do so deliberately.

Since Milestone 13 each response also carries `binding`: every figure in the text, bound
to the packet field, source release, period and match method that licensed it. `hip
explain` refuses to store prose with a figure the packet does not carry, so a binding is
always complete. It is null only for text written before figures were checked, and a
client should say so rather than present that text as verified.

Since Milestone 30 a region carries two readings, one per `audience`: the analyst
reading, which the singular endpoint serves as it always served the preferred one, and
the consumer reading, whose `sections` give each fixed question's answer.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Literal

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy import case, select

from hip.api.deps import SessionDep
from hip.api.params import Window
from hip.packets import Binding, PacketUnavailable, build_packet, still_describes
from hip.warehouse.models import RegionExplanation

router = APIRouter(tags=["explanations"])

# The order the plural endpoint lists readings in: the analyst reading first, as the
# singular endpoint has always led with it.
_AUDIENCE_ORDER = case((RegionExplanation.audience == "analyst", 0), else_=1)

# Says "a language model" rather than "a local language model": since Milestone 12 the
# model may be hosted, and the row itself carries which one wrote it. The disclaimer's
# job is to mark the text as interpretation rather than measurement, which is true of
# every runtime — naming the runtime here would only be a second place to keep correct.
DISCLAIMER = (
    "Generated by a language model from this region's analysis packet. "
    "It is interpretation of computed metrics, not a measurement, and not advice."
)


class ReadingSection(BaseModel):
    """One answer in a consumer reading: which fixed question, and where its answer sits
    in `body`, as character offsets like a citation's."""

    id: str = Field(description="The question's published key, e.g. `rent_or_buy`.")
    heading: str
    start: int
    end: int


class Explanation(BaseModel):
    """A generated narrative, with everything needed to discount it appropriately."""

    kind: Literal["interpretation"] = Field(
        default="interpretation",
        description="Never 'measurement'. This text was written by a model.",
    )
    audience: Literal["analyst", "consumer"] = Field(
        default="analyst",
        description=(
            "Who the reading is written for: `analyst`, the interpretation of the "
            "packet in prose; `consumer`, a bottom line and short answers to fixed "
            "questions in plain language (Milestone 30)."
        ),
    )
    region_id: int
    window: str
    body: str
    sections: list[ReadingSection] | None = Field(
        default=None,
        description=(
            "A consumer reading's answers, in order: each fixed question's key and "
            "heading, and where its answer sits in `body`. Null for an analyst reading."
        ),
    )
    model_id: str
    model_label: str
    runtime: str
    generated_at: datetime
    stale: bool = Field(
        description=(
            "True when the packet's figures have changed since this text was written, "
            "so the prose may describe numbers the warehouse no longer holds. A "
            "re-download that moved no figure does not make text stale."
        )
    )
    binding: Binding | None = Field(
        description=(
            "Every figure in `body`, bound to the packet field, source release, period "
            "and match method that licensed it. Null when the text was written before "
            "figures were checked (Milestone 13): its figures are unverified."
        )
    )
    disclaimer: str = DISCLAIMER


def _served(row: RegionExplanation, *, stale: bool) -> Explanation:
    return Explanation(
        audience=row.audience,  # type: ignore[arg-type]
        region_id=row.region_id,
        window=row.window,
        body=row.body,
        sections=(
            [ReadingSection.model_validate(s) for s in row.sections]
            if row.sections
            else None
        ),
        model_id=row.model_id,
        model_label=row.model_label,
        runtime=row.runtime,
        generated_at=row.generated_at,
        stale=stale,
        binding=Binding.model_validate(row.binding) if row.binding is not None else None,
    )


@router.get(
    "/regions/{region_id}/explanation",
    response_model=Explanation,
    summary="A region's analyst reading (interpretation, not measurement)",
)
def explanation(
    region_id: int,
    session: SessionDep,
    window: Annotated[Window, Query()] = "5y",
) -> Explanation:
    """The analyst reading for one region and window.

    404 when none has been generated. That is the ordinary state of a fresh warehouse,
    not an error condition — the platform is fully usable with no explanations at all,
    which is the SPEC requirement that the AI layer stay optional.

    Shape unchanged since migration 0007, apart from fields added beside it, because it
    is a published contract and the artifact tree behind it exists to be consumed. It
    served the preferred model's reading while a region carried one per model; since
    migration 0019 it serves the region's one analyst reading. Both readings, analyst
    and consumer, are at `/regions/{id}/explanations`.
    """
    row = session.get(RegionExplanation, (region_id, window, "analyst"))
    if row is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"no explanation for region {region_id} over window '{window}'. "
                f"Generate one with `hip explain --region {region_id}`."
            ),
        )

    # Recompute against the warehouse as it stands rather than trusting the stored hash
    # to still describe current data — that comparison is the whole reason the hash is
    # stored. Same reasoning as ARCHITECTURE #42: the durable artifact is not the answer.
    try:
        packet = build_packet(session, region_id, window)
    except PacketUnavailable:
        # The region no longer builds a packet, so staleness cannot be established.
        # False is not a claim that the text is current — the disclaimer still stands.
        return _served(row, stale=False)
    current = still_describes(
        packet, packet_sha256=row.packet_sha256, content_sha256=row.content_sha256
    )
    return _served(row, stale=not current)


class Explanations(BaseModel):
    """A region's readings: the analyst reading, then the consumer reading.

    A list, as it was when it held one reading per model in preference order (Milestone
    19); since migration 0019 it holds one per audience, each saying which it is.
    """

    region_id: int
    window: str
    explanations: list[Explanation]


@router.get(
    "/regions/{region_id}/explanations",
    response_model=Explanations,
    summary="A region's readings, analyst then consumer",
)
def explanations(
    region_id: int,
    session: SessionDep,
    window: Annotated[Window, Query()] = "5y",
) -> Explanations:
    """Every stored reading for one region and window: analyst first, then consumer.

    Until Milestone 30 this served every model's reading of one packet side by side, so
    a reader could see models disagree about identical numbers. It now serves the two
    readings written for two readers, each from the first model on its audience's list
    that wrote one fit to publish, and each naming that model.

    404 rather than an empty list when nothing has been generated, matching the singular
    endpoint: `hip publish` treats a 404 as a skip, so an empty body would put a file
    with no content in the artifact tree for every region that has no explanation.
    """
    rows = (
        session.execute(
            select(RegionExplanation)
            .where(
                RegionExplanation.region_id == region_id,
                RegionExplanation.window == window,
            )
            .order_by(_AUDIENCE_ORDER)
        )
        .scalars()
        .all()
    )
    if not rows:
        raise HTTPException(
            status_code=404,
            detail=(
                f"no explanations for region {region_id} over window '{window}'. "
                f"Generate them with `hip explain --region {region_id}`."
            ),
        )

    # The packet is built once and compared per row: the two readings are generated
    # independently, so one can be current while the other is stale, and collapsing
    # that to a single flag would misreport both.
    try:
        packet = build_packet(session, region_id, window)
    except PacketUnavailable:
        packet = None

    return Explanations(
        region_id=region_id,
        window=window,
        explanations=[
            _served(
                row,
                stale=packet is not None
                and not still_describes(
                    packet,
                    packet_sha256=row.packet_sha256,
                    content_sha256=row.content_sha256,
                ),
            )
            for row in rows
        ],
    )
