"""Model-written explanations, served as interpretation and labeled as such.

Read-only, like every other endpoint. `hip explain` generates and stores; this reads a
row back (ARCHITECTURE #6). No request path loads a model — a model load is seconds and
gigabytes, and on 16GB of unified memory a resident model would push the rest of the
platform into swap.

The response is shaped so a consumer cannot present this as a measurement by accident.
`kind` is the literal string `interpretation`, the generating model is named, and `stale`
says whether the numbers moved since the text was written. A client that ignores all
three has to do so deliberately.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Literal

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy import select

from hip.api.deps import SessionDep
from hip.api.params import Window
from hip.packets import PacketUnavailable, build_packet, packet_hash
from hip.warehouse.models import RegionExplanation

router = APIRouter(tags=["explanations"])

# Says "a language model" rather than "a local language model": since Milestone 12 the
# model may be hosted, and the row itself carries which one wrote it. The disclaimer's
# job is to mark the text as interpretation rather than measurement, which is true of
# every runtime — naming the runtime here would only be a second place to keep correct.
DISCLAIMER = (
    "Generated by a language model from this region's analysis packet. "
    "It is interpretation of computed metrics, not a measurement, and not advice."
)


class Explanation(BaseModel):
    """A generated narrative, with everything needed to discount it appropriately."""

    kind: Literal["interpretation"] = Field(
        default="interpretation",
        description="Never 'measurement'. This text was written by a model.",
    )
    region_id: int
    window: str
    body: str
    model_id: str
    model_label: str
    runtime: str
    generated_at: datetime
    stale: bool = Field(
        description=(
            "True when the packet has changed since this text was written, so the "
            "prose may describe numbers the warehouse no longer holds."
        )
    )
    disclaimer: str = DISCLAIMER


@router.get(
    "/regions/{region_id}/explanation",
    response_model=Explanation,
    summary="Model-written explanation for a region (interpretation, not measurement)",
)
def explanation(
    region_id: int,
    session: SessionDep,
    window: Annotated[Window, Query()] = "5y",
) -> Explanation:
    """The preferred stored explanation for one region and window.

    404 when none has been generated. That is the ordinary state of a fresh warehouse,
    not an error condition — the platform is fully usable with no explanations at all,
    which is the SPEC requirement that the AI layer stay optional.

    Shape deliberately unchanged by migration 0010. A region may now hold several
    models' readings, and this endpoint still answers with one, because it is a
    published contract and the artifact tree behind it exists to be consumed. Callers
    that want the comparison ask `/regions/{id}/explanations` instead.
    """
    # `LIMIT 1` over rank rather than `scalar_one_or_none`: since migration 0010 a
    # region can carry one explanation per model, and this endpoint's contract is a
    # single object. Rank 1 is the preferred model at the time the rows were written.
    row = session.execute(
        select(RegionExplanation)
        .where(
            RegionExplanation.region_id == region_id,
            RegionExplanation.window == window,
        )
        .order_by(RegionExplanation.rank, RegionExplanation.model_id)
        .limit(1)
    ).scalar_one_or_none()
    if row is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"no explanation for region {region_id} over window '{window}'. "
                f"Generate one with `hip explain --region {region_id}`."
            ),
        )

    # Recompute against the warehouse as it stands rather than trusting the stored hash
    # to still describe current data — that comparison is the whole reason the hash is
    # stored. Same reasoning as ARCHITECTURE #42: the durable artifact is not the answer.
    try:
        stale = packet_hash(build_packet(session, region_id, window)) != row.packet_sha256
    except PacketUnavailable:
        # The region no longer builds a packet, so staleness cannot be established.
        # False is not a claim that the text is current — the disclaimer still stands.
        stale = False

    return Explanation(
        region_id=row.region_id,
        window=row.window,
        body=row.body,
        model_id=row.model_id,
        model_label=row.model_label,
        runtime=row.runtime,
        generated_at=row.generated_at,
        stale=stale,
    )


class Explanations(BaseModel):
    """Every model's reading of one region's packet, in preference order.

    A list rather than a map keyed by model, because the order is the information: it is
    the preference list's own ranking, and a JSON object does not promise to keep it.
    """

    region_id: int
    window: str
    explanations: list[Explanation]


@router.get(
    "/regions/{region_id}/explanations",
    response_model=Explanations,
    summary="Every model's explanation for a region, in preference order",
)
def explanations(
    region_id: int,
    session: SessionDep,
    window: Annotated[Window, Query()] = "5y",
) -> Explanations:
    """All stored explanations for one region and window, ordered by rank.

    The point of serving them together is that the numbers underneath are identical, so
    the differences are the models' own. That is the most honest demonstration the
    platform can make of its own SPEC requirement that a reader can always tell
    interpretation from measurement — a disclaimer asserts it, five readings of one
    packet show it.

    404 rather than an empty list when nothing has been generated, matching the singular
    endpoint: `hip publish` treats a 404 as a skip, so an empty body would put a file
    with no content in the artifact tree for every region that has no explanation.
    """
    rows = (
        session.execute(
            select(RegionExplanation)
            .where(
                RegionExplanation.region_id == region_id,
                RegionExplanation.window == window,
            )
            .order_by(RegionExplanation.rank, RegionExplanation.model_id)
        )
        .scalars()
        .all()
    )
    if not rows:
        raise HTTPException(
            status_code=404,
            detail=(
                f"no explanations for region {region_id} over window '{window}'. "
                f"Generate them with `hip explain --region {region_id} --all`."
            ),
        )

    # Staleness is computed once against the current warehouse and compared per row:
    # models are generated independently, so one reading can be current while another
    # is stale, and collapsing that to a single flag would misreport both.
    try:
        current = packet_hash(build_packet(session, region_id, window))
    except PacketUnavailable:
        current = None

    return Explanations(
        region_id=region_id,
        window=window,
        explanations=[
            Explanation(
                region_id=row.region_id,
                window=row.window,
                body=row.body,
                model_id=row.model_id,
                model_label=row.model_label,
                runtime=row.runtime,
                generated_at=row.generated_at,
                stale=current is not None and row.packet_sha256 != current,
            )
            for row in rows
        ],
    )
