import type { Metadata } from "next";
import Link from "next/link";

import { Crumbs } from "@/components/Crumbs";
import { Masthead } from "@/components/Masthead";
import { dayLabel } from "@/lib/freshness";
import { CONTACT_EMAIL, FRED_TERMS_URL, OPERATOR, POLICIES_UPDATED, PRIVACY_EMAIL, REPO_URL } from "@/lib/site";
import { pageMetadata } from "@/lib/meta";

export const metadata: Metadata = pageMetadata({
  title: "Terms of use — Housing",
  description:
    "Who runs this site, what its figures are and are not, the terms each data source sets, " +
    "and the FRED® API terms every visitor agrees to.",
  path: "/terms",
});

/**
 * The site's terms of use (ARCHITECTURE #357). Written to say only what the site keeps:
 * it is free and non-commercial (#323), its figures belong to their publishers, and it
 * cannot grant terms it was not given. FRED's API terms require an application used by
 * others to state in its terms of use that using it binds the user to FRED's (#278);
 * that sentence is here, and a test holds it.
 */
export default function TermsPage() {
  return (
    <>
      <Masthead affordability={{ kind: "hidden" }} />
      <main id="main-content" tabIndex={-1} className="shell atlas-page atlas-ledger quiet-county quiet-history legal-page">
        <header className="page-head">
          <div>
            <Crumbs trail={[{ href: "/", label: "United States" }]} here="Terms of use" />
            <h1 className="page-title">Terms of use</h1>
            <p className="meta">Last updated {dayLabel(POLICIES_UPDATED)}. See also the <Link href="/privacy">privacy policy</Link>.</p>
          </div>
        </header>

        <section className="section" aria-labelledby="terms-who">
          <h2 id="terms-who">Who runs this site</h2>
          <p>
            Housing Intelligence is run by {OPERATOR}, an independent developer. It is free to use,
            needs no account, and carries no advertising, sponsorship or paid tier: it is not run
            for commercial purposes. By using it you agree to these terms.
          </p>
        </section>

        <section className="section" aria-labelledby="terms-what">
          <h2 id="terms-what">What the figures are, and are not</h2>
          <ul>
            <li>
              Information drawn from public sources, for understanding a place. It is not
              financial, legal, tax, insurance or real-estate advice, and not an appraisal of any
              property.
            </li>
            <li>
              Figures can be out of date, revised by their publisher, estimated or modelled; each
              page says which, and how current each source is is on the{" "}
              <Link href="/freshness">freshness page</Link>. Check the publisher or the official
              record before relying on one for a decision.
            </li>
            <li>
              The written summaries are generated by AI models and checked against the figures
              before they are published, but they can still be wrong. The figures beside them are
              the record.
            </li>
          </ul>
        </section>

        <section className="section" aria-labelledby="terms-data">
          <h2 id="terms-data">The data belongs to its publishers</h2>
          <p>
            Every figure comes from a public source named in the footer of each page, under that
            publisher&rsquo;s own terms. Some sources allow non-commercial use only, Zillow among
            them, and some figures are shown here but left out of downloads because their terms
            allow display only. This site cannot grant rights to data it was not given: reusing
            a figure means following its publisher&rsquo;s terms.
          </p>
          <p>
            <strong>FRED®.</strong> This site uses the FRED® API. By using this site, you agree to
            be bound by the{" "}
            <a href={FRED_TERMS_URL} rel="noreferrer noopener" target="_blank">
              FRED® API Terms of Use
            </a>
            . This product uses the FRED® API but is not endorsed or certified by the Federal
            Reserve Bank of St. Louis.
          </p>
        </section>

        <section className="section" aria-labelledby="terms-tax">
          <h2 id="terms-tax">The property tax lookup</h2>
          <p>
            The lookup shows public tax-assessment records by address, with no owner names. Do not
            use it to find, contact or harass anyone. Under New Jersey&rsquo;s Daniel&rsquo;s Law, a
            covered person can have their home address removed: email{" "}
            <a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a> with the address and town.
          </p>
        </section>

        <section className="section" aria-labelledby="terms-code">
          <h2 id="terms-code">The code</h2>
          <p>
            The site&rsquo;s code is free software under the GNU Affero General Public License v3.0,
            and{" "}
            <a href={REPO_URL} rel="noreferrer noopener" target="_blank">
              its source is public
            </a>
            . That licence covers the code only, not the data.
          </p>
        </section>

        <section className="section" aria-labelledby="terms-warranty">
          <h2 id="terms-warranty">No warranty</h2>
          <p>
            The site is provided as it is, without any warranty that it is accurate, complete or
            available. To the extent the law allows, {OPERATOR} is not liable for any loss arising
            from its use.
          </p>
        </section>

        <section className="section" aria-labelledby="terms-changes">
          <h2 id="terms-changes">Changes and contact</h2>
          <p>
            These terms may change; the date at the top says when they last did. Questions or
            corrections: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
          </p>
        </section>
      </main>
    </>
  );
}
